package com.catgen;

public class MailMsgs {
	public static final String OPENENTRY_ID = "#OPENENTRY_ID#";
	public static final String OPENENTRY_NAME= "#OPENENTRY_NAME#";
	public static final String ACCOUNT_TYPE = "#ACCOUNT_TYPE#";
	public static final String AUTH_CODE= "#AUTH_CODE#";
	public static final String EMAIL_ID= "#EMAIL_ID#";
	public static final String PASSWORD= "#PASSWORD#";
	public static final String ACTIVATION_CODE= "#ACTIVATION_CODE#";
	public static final String RECEIVER_CATEGORY = "#RECEIVER_CATEGORY#";
	public static final String OPENENTRY_ID2 = "#OPENENTRY_ID2#";
	
	public static final String OPENENTRY_MAIL_ID = "sales.openentry@gmail.com";
	public static final String WELCOME = "Welcome to OpenEntry";
	public static final String AUTHENTICATE_EMAIL_SUBJECT = "OpenEntry - Email ID Validation";
	public static final String AUTHENTICATE_EMAIL_BODY = "Dear #OPENENTRY_ID#,\n\nPlease enter the eight character code given below in the registration screen to authenticate your email account:\n\nCode: #ACTIVATION_CODE#\n\nThanks and Regards,\nOpenEntry.com\n";
	public static final String REGISTRATION_NOTIFICATION_SUBJECT = "OpenEntry - Account Registered";
	public static final String REGISTRATION_NOTIFICATION_BODY = "\nDear #OPENENTRY_ID#,\n\nThank you for registering a [#ACCOUNT_TYPE#] account with us.\nThe link to the network market website is:\nhttp://nm.openentry.com/#OPENENTRY_ID#\n\nYou can log into your account at http://nm.openentry.com using the below credentials:\n\nUser ID : #OPENENTRY_ID#\nPassword : #PASSWORD#\n\n\n\nThanks and Regards,\n\nOpenEntry User Support Team\nSupport@OpenEntry.com\n\n\n";
	public static final String REGISTRATION_NOTIFICATION_BODY_REFERRER = "\nDear #OPENENTRY_ID#,\n\nThank you for registering a [#ACCOUNT_TYPE#] account with us.\n\nYou can log into your account at http://nm.openentry.com using the below credentials:\n\nUser ID : #OPENENTRY_ID#\nPassword : #PASSWORD#\n\n\n\nThanks and Regards,\n\nOpenEntry User Support Team\nSupport@OpenEntry.com\n\n\n";
	public static final String VALIDATION_SUCCESSFUL_BODY = "\nDear #OPENENTRY_ID#,\n\nYour account has been validated by OpenEntry. You will now be able to login to your account using the login credentials sent to you earlier upon registration.\n\nThanks for signing up. We're confident that OpenEntry will be a great business portal for you!\n\nThanks and Regards,\n\nOpenEntry\nwww.openentry.com\n";
	public static final String PASSWORD_RESET_NOTIFICATION_SUBJECT = "OpenEntry - Password Reset Notification";
	public static final String PASSWORD_RESET_NOTIFICATION_BODY = "\nDear #OPENENTRY_ID#,\n\nYour account password has been reset.\nYour new password is: #PASSWORD#\n\n\nThanks and Regards,\n\nOpenEntry.com";
	public static final String PASSWORD_CHANGE_NOTIFICATION_SUBJECT = "OpenEntry - Your new password";
	public static final String PASSWORD_CHANGE_NOTIFICATION_BODY = "\nDear #OPENENTRY_ID#,\n\nYou have changed your password from OpenEntry Network Market Management System panel.\nYour new password is: #PASSWORD#\n\n\nThanks and Regards,\n\nOpenEntry.com";
	public static final String EMAIL_AUTHENTICATION_SUBJECT = "OpenEntry - Email Authentication Code";
	public static final String EMAIL_AUTHENTICATION_BODY = "\nHello from OpenEntry.\n\nYour Email Authentication code is:\n#AUTH_CODE#\n\n\nThanks and Regards,\n\nOpenEntry.com\n";
	public static final String NOTIFICATION_MESSAGE = "\n\n\n-----------------------------------------------------------------------------------\nThis is a notification mail. Please do not reply to this mail.";
	public static final String MAIL_FOOTER = "\n \n \n ----------------------------------------------------------------------------------------------------------------------------------------\n Note:\n \n Sender Name : #OPENENTRY_NAME#\n Sender Code : #OPENENTRY_ID#\n Sender type : #ACCOUNT_TYPE#\n Sender Email : #EMAIL_ID#\n Sent to : #RECEIVER_CATEGORY#\n \n This is an autogenerated email. Please do not reply to this message.\n You can write to  the Sender in the Email ID mentioned above (Sender Email).\n \n \n Thanks and Regards,\n OpenEntry.com\n \n ----------------------------------------------------------------------------------------------------------------------------------------\n \n";
	public static final String REGISTRATION_NOTIFICATION_FOR_GAE_CATALOG = "\nDear #OPENENTRY_ID#,\n\nYour OpenEntry Network Market Management System account has been created.\nCredentials given below:\n\nUser ID: #OPENENTRY_ID#\nPassword: #PASSWORD#\n\n\nThanks and Regards,\nOpenEntry.com";
	public static final String ADD_NOTIFICATION_SUBJECT = "OpenEntry - Added to Network Market";
	public static final String ADD_NOTIFICATION_BODY = "Dear #OPENENTRY_ID#,\nYour catalog is now associated with Network Market "+Constants.OE_URL+"/#OPENENTRY_ID2#.\n\nThanks and Regards,\nOpenEntry.com\n";
	public static final String ADDED_BY_SUPER_NM_BODY = "Dear #OPENENTRY_ID#,\nYour Network Market is now a sub-market to Network Market "+Constants.OE_URL+"/#OPENENTRY_ID2#.\n\nThanks and Regards,\nOpenEntry.com\n";
	public static final String ADD_APPROVED_NOTIFICATION_SUBJECT = "OpenEntry - Request to join #OPENENTRY_ID# approved.";
	public static final String ADD_APPROVED_NOTIFICATION_BODY = "Dear #OPENENTRY_ID#,\n#OPENENTRY_ID2# has approved your request to join the network market. You can now log in to http://catalog.openentry.com and make necessary payment, after which your catalog will be instantly available in the Network Market website.\n\nThanks and Regards,\nOpenEntry.com\n";
	public static final String CACHE="remove cache";
	
	public static final String[] MAIL_RECEIVER_CATEGORY= {
		"All the vendors available in OpenEntry",
		"All the vendors present in this Network Market",
		"Only the featured vendors present in this Network Market",
		"Only the non-featured vendors present in this Network Market"
	};
}
